---

- hosts: all
  gather_facts: no
  tasks:

    - community.docker.docker_network:
        name: devops-example

    - community.docker.docker_container:
        name: app
        # Обязатлеьно указываем тег, который хотим деплоить
        # Если образа на сервере нет, Ansible его автоматически скачает
        image: "hexletcomponents/devops-example-app:{{ version }}"
        # Подключаем супервизор
        # Если контейнер остановится, например, из-за ошибок
        # супервизор докера его перезапустить
        restart_policy: always
        # Запускаем если не запущен
        state: started
        networks:
          - name: devops-example
        # Делаем доступным снаружи
        ports:
          - 3000:3000
        env: # Настраиваем
          NODE_ENV: production

    - community.docker.docker_container:
        name: caddy
        image: "hexletcomponents/devops-example-caddy:{{ version }}"
        restart_policy: always
        state: started
        networks:
          - name: devops-example
        ports:
          - 80:80
          - 443:443
