name: release

on:
  create:
    tags:
      - v*

env:
  APP_IMAGE_NAME: hexletcomponents/devops-example-app
  CADDY_IMAGE_NAME: hexletcomponents/devops-example-caddy

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: docker/setup-qemu-action@v1
      # - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker pull ${{ env.APP_IMAGE_NAME }}:latest
      - run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}
      - run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      - run: docker pull ${{ env.CADDY_IMAGE_NAME }}:latest
      - run: docker tag ${{ env.CADDY_IMAGE_NAME }}:latest ${{ env.CADDY_IMAGE_NAME }}:${{ github.ref_name }}
      - run: docker push ${{ env.CADDY_IMAGE_NAME }}:${{ github.ref_name }}
